### ISSUE TITLE
Sumatra PDF not working with Latex-Plus

### ISSUE THREAD

**Issue by WoodyWoodsta** [randy3k/LaTeX-Plus#26]
Hi

I am setting up a Latex toolchain for some university reports and assignments, and have decided to use Latex-Plus (used Latex-Tools in the past). I see to be having issues with Sumatra PDF v3.0, it will not open after build. I've got the sumatra directory in my path variable, as well as the path defined in the package settings file. I can open documents in sumatra via command line as well.

This is the error that is being thrown in Sublime Text when I build a tex file:

```
['latexmk', '-quiet', '-pdf', '-e', "$pdflatex='pdflatex -synctex=1 --shell-escape %O %S'", 'EEE2039E Project Report.tex']
!TEX root =  C:\_ITDev\Documents\EEE2039E Project Report\EEE2039E Project Report.tex
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 543, in run_
    return self.run(edit, **args)
  File "jump in C:\Users\Sean\AppData\Roaming\Sublime Text 3\Installed Packages\LaTeX-Plus.sublime-package", line 81, in run
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 306: invalid start byte
```

Not sure what this means to be honest! Any ideas?

Thanks!
Sean

**Comment by randy3k** [comment]
are your windows not in English? I think it has something to do with a running program with a different locale than utf8.

**Comment by WoodyWoodsta** [comment]
I'll have a look at the encoding. I'm running windows in English (South
Africa), could that be an issue?

**Comment by randy3k** [comment]
Could you open sublime console (ctrl + `) and run `import subprocess; subprocess.check_output(["tasklist"])` and paste the result here?

**Comment by WoodyWoodsta** [comment]
Here we go:

```
>>>import subprocess; subprocess.check_output(["tasklist"])
b'\r\nImage Name                     PID Session Name        Session#    Mem Usage\r\n========================= ======== ================ =========== ============\r\nSystem Idle Process              0 Services                   0          4 K\r\nSystem                           4 Services                   0      6\xff244 K\r\nsmss.exe                       288 Services                   0        828 K\r\ncsrss.exe                      408 Services                   0      4\xff120 K\r\nwininit.exe                    488 Services                   0      3\xff232 K\r\ncsrss.exe                      496 Console                    1     24\xff832 K\r\nservices.exe                   544 Services                   0      5\xff596 K\r\nlsass.exe                      552 Services                   0      8\xff384 K\r\nwinlogon.exe                   600 Console                    1      4\xff936 K\r\nsvchost.exe                    660 Services                   0     10\xff028 K\r\nsvchost.exe                    692 Services                   0      7\xff100 K\r\nnvvsvc.exe                     776 Services                   0      6\xff064 K\r\ndwm.exe                        808 Console                    1     27\xff772 K\r\nnvvsvc.exe                     888 Console                    1      9\xff824 K\r\nsvchost.exe                    912 Services                   0     18\xff688 K\r\nsvchost.exe                    940 Services                   0     31\xff356 K\r\nsvchost.exe                    980 Services                   0     14\xff952 K\r\nnvxdsync.exe                   312 Console                    1     13\xff516 K\r\nsvchost.exe                    420 Services                   0     40\xff460 K\r\nsvchost.exe                    796 Services                   0     14\xff752 K\r\nspoolsv.exe                   1300 Services                   0      9\xff524 K\r\nsvchost.exe                   1336 Services                   0      9\xff112 K\r\nsvchost.exe                   1396 Services                   0     21\xff396 K\r\narmsvc.exe                    1500 Services                   0      4\xff008 K\r\nAEADISRV.EXE                  1540 Services                   0      2\xff228 K\r\nBtwRSupportService.exe        1556 Services                   0      4\xff416 K\r\nremoting_host.exe             1596 Services                   0      5\xff328 K\r\nofficeclicktorun.exe          1620 Services                   0     25\xff544 K\r\ndasHost.exe                   1672 Services                   0      3\xff348 K\r\nremoting_host.exe             1716 Services                   0     10\xff428 K\r\nFCUpdateService.exe           1800 Services                   0      3\xff892 K\r\nsvchost.exe                   1880 Services                   0      6\xff040 K\r\nMsMpEng.exe                   1924 Services                   0     46\xff512 K\r\nXAudio64.exe                  1992 Services                   0      2\xff812 K\r\nNisSrv.exe                    2364 Services                   0      4\xff556 K\r\nexplorer.exe                  2520 Console                    1     73\xff100 K\r\ntaskhostex.exe                2536 Console                    1     11\xff056 K\r\nSearchIndexer.exe             3056 Services                   0     19\xff932 K\r\nSynTPEnh.exe                  3132 Console                    1     10\xff300 K\r\nSynTPHelper.exe               3240 Console                    1      2\xff948 K\r\nchrome.exe                    3260 Console                    1    156\xff636 K\r\nSkype.exe                     3312 Console                    1     72\xff708 K\r\ngoogledrivesync.exe           3344 Console                    1      3\xff372 K\r\nfdm.exe                       3420 Console                    1     26\xff288 K\r\nchrome.exe                    3460 Console                    1     62\xff144 K\r\nQLBCtrl.exe                   3500 Console                    1     10\xff308 K\r\nsmax4pnp.exe                  3556 Console                    1      7\xff472 K\r\nchrome.exe                    3656 Console                    1     59\xff428 K\r\nchrome.exe                    3692 Console                    1     30\xff988 K\r\nchrome.exe                    3704 Console                    1     82\xff296 K\r\nchrome.exe                    3712 Console                    1     68\xff076 K\r\nVolCtrl.exe                   3864 Console                    1      6\xff028 K\r\ngoogledrivesync.exe           3896 Console                    1     54\xff796 K\r\nhpqWmiEx.exe                  3920 Services                   0      5\xff788 K\r\nWmiPrvSE.exe                  4028 Services                   0      6\xff356 K\r\nCom4QLBEx.exe                 2916 Services                   0      5\xff148 K\r\nHpqToaster.exe                1684 Console                    1      6\xff884 K\r\npushbullet_client.exe         2248 Console                    1     59\xff828 K\r\nTaskmgr.exe                   3760 Console                    1     27\xff488 K\r\nwmpnetwk.exe                  2684 Services                   0      3\xff724 K\r\ndllhost.exe                   1696 Services                   0      8\xff084 K\r\nchrome.exe                    4260 Console                    1     65\xff960 K\r\ncmd.exe                       4284 Console                    1      2\xff828 K\r\nconhost.exe                   1820 Console                    1      4\xff276 K\r\nnativeproxy.exe               1892 Console                    1      3\xff412 K\r\nchrome.exe                    1472 Console                    1     63\xff760 K\r\naudiodg.exe                   2456 Services                   0      9\xff304 K\r\ncmd.exe                       1532 Console                    1      2\xff764 K\r\nconhost.exe                   4728 Console                    1      4\xff308 K\r\nnativeproxy.exe               4400 Console                    1      3\xff440 K\r\ncmd.exe                       5300 Console                    1      2\xff760 K\r\nconhost.exe                   4212 Console                    1      4\xff324 K\r\nnativeproxy.exe               4472 Console                    1      3\xff416 K\r\nchrome.exe                    5952 Console                    1    133\xff628 K\r\ncmd.exe                       6068 Console                    1      2\xff756 K\r\nconhost.exe                   5480 Console                    1      4\xff212 K\r\nnativeproxy.exe               4180 Console                    1      3\xff416 K\r\nsublime_text.exe              5644 Console                    1     51\xff796 K\r\nplugin_host.exe               4352 Console                    1     46\xff644 K\r\nchrome.exe                    5340 Console                    1     69\xff516 K\r\nchrome.exe                    4364 Console                    1     18\xff228 K\r\nWmiPrvSE.exe                  2840 Services                   0      6\xff740 K\r\ntasklist.exe                  5212 Console                    1      5\xff720 K\r\nconhost.exe                   2432 Console                    1      4\xff804 K\r\n'
```

**Comment by randy3k** [comment]
should be fixed by eea15ae

**Comment by WoodyWoodsta** [comment]
Will give it a shot sometime today and give feedback. Thanks!

**Comment by WoodyWoodsta** [comment]
Just tested and everything is working well! Thank you for the fix!
